import requests

print(" ")
print(" ")
print("Salam!")
print(" ")
print(" ")
print("Be Download File Khosh Amadid!")
print(" ")
print(" ")
print("Momken Ast Nesbat Be Sorat Internet Kami Tol Bekeshad!")
print(" ")
print(" ")
url = input("Lotfan Link File  Ra Vared Farmaiid--------->")
print(" ")
print(" ")
name = input("Be Che Esmi Mikhaid File Ra Zakhire Konid?--------->")
print(" ")
print(" ")
print("Format File! baraye mesal baraye video=mp4|music=mp3|aks=png|file feshorde=zip| va ya formati ke mikhavahid va ya format khod file")
print(" ")
print(" ")
print(" ")
print("Mitavanid ba Search Dar Net Anva Format Ha Ra Bebinid!")
print(" ")
print(" ")
print(" ")
format = input("Lotfan Format File Ra Vared Namaiid--------->")
f1 = "."
print(" ")
print(" ")
print("Lotfan Sabr Namaiid Momken Ast Tool Bekeshad!")
print(" ")
print(" ")
page = requests.get(url)
print("200=dar Hal Download | 404=Etesal Namovafag")
print(" ")
print("vaziat file:",page.status_code)

r = requests.get(url)
with open(name+f1+format,"wb") as code:
    code.write(r.content)
print(" ")
print(" ")
print("95% Download Shod")
print("96% Download Shod")
print("97% Download Shod")
print("98% Download Shod")
print("99% Download Shod")
print("100% Download Shod")
print("Download shod!")
print(" ")
print(" ")
print("Dar Hal Zakhire Sazi.")
print("Dar Hal Zakhire Sazi..")
print("Dar Hal Zakhire Sazi...")
print("Zakhire Shod!")
print(" ")
print("Baraye Baste Shodan Barname Enter Bezanid.")

k=input()