import requests

print(" ")
print(" ")
print("Hi!")
print(" ")
print(" ")
print("Welcome To The File Downloader!")
print(" ")
print(" ")
print("Depending on your internet speed, it may take some time to download")
print(" ")
print(" ")
url = input("Please Insert Link--------->")
print(" ")
print(" ")
name = input("What name do you want to save your file?--------->")
print(" ")
print(" ")
print("To see various formats, please search it on Google")
print(" ")
print(" ")
print(" ")
print("")
print("Enjoy downloading")
print(" ")
print(" ")
format = input("Please Insert File Format--------->")
f1 = "."
print(" ")
print(" ")
print("Please wait, it may take a while")
print(" ")
print(" ")
page = requests.get(url)
print("200=Downloading | 404=Download Faild")
print(" ")
print("File Status:",page.status_code)

r = requests.get(url)
with open(name+f1+format,"wb") as code:
    code.write(r.content)
print(" ")
print(" ")
print("95% Downloaded")
print("96% Downloaded")
print("97% Downloaded")
print("98% Downloaded")
print("99% Downloaded")
print("100% Downloaded")
print("Downloaded successfully")
print(" ")
print(" ")
print("Saving.")
print("Saving..")
print("Saving...")
print("Saved!")
print(" ")
print("please use Enter Key to close app!")

k=input()